package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class EnteringDataController {
	@FXML
	private Button submitButton;
	@FXML
	private Button cancelButton;

	// Event Listener on Button[#submitButton].onAction
	@FXML
	public void submitButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
